//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.SchoolUp.Recursos {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Configuracoes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configuracoes() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modelo.SchoolUp.Recursos.Configuracoes", typeof(Configuracoes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Anterior.
        /// </summary>
        public static string CalendarioBotaoAnterior {
            get {
                return ResourceManager.GetString("CalendarioBotaoAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar.
        /// </summary>
        public static string CalendarioBotaoFechar {
            get {
                return ResourceManager.GetString("CalendarioBotaoFechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hoje.
        /// </summary>
        public static string CalendarioBotaoHoje {
            get {
                return ResourceManager.GetString("CalendarioBotaoHoje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Próximo.
        /// </summary>
        public static string CalendarioBotaoProximo {
            get {
                return ResourceManager.GetString("CalendarioBotaoProximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a dd/mm/yy.
        /// </summary>
        public static string CalendarioFormatoData {
            get {
                return ResourceManager.GetString("CalendarioFormatoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hora.
        /// </summary>
        public static string CalendarioHora {
            get {
                return ResourceManager.GetString("CalendarioHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Janeiro&apos;,&apos;Fevereiro&apos;,&apos;Março&apos;,&apos;Abril&apos;,&apos;Maio&apos;,&apos;Junho&apos;,&apos;Julho&apos;,&apos;Agosto&apos;,&apos;Setembro&apos;,&apos;Outubro&apos;,&apos;Novembro&apos;,&apos;Dezembro&apos;.
        /// </summary>
        public static string CalendarioMesLong {
            get {
                return ResourceManager.GetString("CalendarioMesLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Jan&apos;,&apos;Fev&apos;,&apos;Mar&apos;,&apos;Abr&apos;,&apos;Mai&apos;,&apos;Jun&apos;,&apos;Jul&apos;,&apos;Ago&apos;,&apos;Set&apos;,&apos;Out&apos;,&apos;Nov&apos;,&apos;Dez&apos;.
        /// </summary>
        public static string CalendarioMesShort {
            get {
                return ResourceManager.GetString("CalendarioMesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Minuto.
        /// </summary>
        public static string CalendarioMinuto {
            get {
                return ResourceManager.GetString("CalendarioMinuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Domingo&apos;, &apos;Segunda&apos;, &apos;Terça&apos;, &apos;Quarta&apos;, &apos;Quinta&apos;, &apos;Sexta&apos;, &apos;Sábado&apos;, &apos;Domingo&apos;.
        /// </summary>
        public static string CalendarioSemanaLong {
            get {
                return ResourceManager.GetString("CalendarioSemanaLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;D&apos;,&apos;S&apos;,&apos;T&apos;,&apos;Q&apos;,&apos;Q&apos;,&apos;S&apos;,&apos;S&apos;,&apos;D&apos;.
        /// </summary>
        public static string CalendarioSemanaMin {
            get {
                return ResourceManager.GetString("CalendarioSemanaMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Dom&apos;,&apos;Seg&apos;,&apos;Ter&apos;,&apos;Qua&apos;,&apos;Qui&apos;,&apos;Sex&apos;,&apos;Sáb&apos;,&apos;Dom&apos;.
        /// </summary>
        public static string CalendarioSemanaShort {
            get {
                return ResourceManager.GetString("CalendarioSemanaShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;&gt;.
        /// </summary>
        public static string CaracteresProibidos {
            get {
                return ResourceManager.GetString("CaracteresProibidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C:\\\\Logs\\\\Padrao\\\\ErroLog_{0}.txt.
        /// </summary>
        public static string FormatoArquivoLog {
            get {
                return ResourceManager.GetString("FormatoArquivoLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a a357864f-600a-4bea-a989-15fa103b28c2.
        /// </summary>
        public static string IdUsuarioLogger {
            get {
                return ResourceManager.GetString("IdUsuarioLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a pt-BR.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 9?99 Ampères.
        /// </summary>
        public static string MascaraAmpere {
            get {
                return ResourceManager.GetString("MascaraAmpere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 9999.
        /// </summary>
        public static string MascaraAno {
            get {
                return ResourceManager.GetString("MascaraAno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 99.999-999.
        /// </summary>
        public static string MascaraCEP {
            get {
                return ResourceManager.GetString("MascaraCEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 99.999.999/9999-99.
        /// </summary>
        public static string MascaraCNPJ {
            get {
                return ResourceManager.GetString("MascaraCNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 99/99/9999.
        /// </summary>
        public static string MascaraData {
            get {
                return ResourceManager.GetString("MascaraData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 99/99/9999 99:99.
        /// </summary>
        public static string MascaraDataTempo {
            get {
                return ResourceManager.GetString("MascaraDataTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a R$ .
        /// </summary>
        public static string MascaraMonetaria {
            get {
                return ResourceManager.GetString("MascaraMonetaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _.
        /// </summary>
        public static string MascaraPlaceHolder {
            get {
                return ResourceManager.GetString("MascaraPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a (99) 9999-9999.
        /// </summary>
        public static string MascaraTelefone {
            get {
                return ResourceManager.GetString("MascaraTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 9?99999 Volts.
        /// </summary>
        public static string MascaraVolt {
            get {
                return ResourceManager.GetString("MascaraVolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 9?99999 Watts.
        /// </summary>
        public static string MascaraWatt {
            get {
                return ResourceManager.GetString("MascaraWatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ADMCLINICALUP.
        /// </summary>
        public static string PerfilAdminClinicalUp {
            get {
                return ResourceManager.GetString("PerfilAdminClinicalUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Escolha a disciplina.
        /// </summary>
        public static string SelecioneUmaDisciplina {
            get {
                return ResourceManager.GetString("SelecioneUmaDisciplina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Escolha a turma.
        /// </summary>
        public static string SelecioneUmaTurma {
            get {
                return ResourceManager.GetString("SelecioneUmaTurma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um item.
        /// </summary>
        public static string SelecioneUmItem {
            get {
                return ResourceManager.GetString("SelecioneUmItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a dd/MM/yyyy.
        /// </summary>
        public static string VbFormatoData {
            get {
                return ResourceManager.GetString("VbFormatoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a dd/MM/yyyy hh:mm.
        /// </summary>
        public static string VbFormatoDataHora {
            get {
                return ResourceManager.GetString("VbFormatoDataHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a yyyyMMddHHmmssfff.
        /// </summary>
        public static string VbFormatoDataHoraCompleta {
            get {
                return ResourceManager.GetString("VbFormatoDataHoraCompleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a yyyyMMdd.
        /// </summary>
        public static string VbFormatoDataSerial {
            get {
                return ResourceManager.GetString("VbFormatoDataSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a #,###.00.
        /// </summary>
        public static string VbFormatoMonetario {
            get {
                return ResourceManager.GetString("VbFormatoMonetario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a #.####.
        /// </summary>
        public static string VbFormatoNumerico {
            get {
                return ResourceManager.GetString("VbFormatoNumerico", resourceCulture);
            }
        }
    }
}
