//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.SchoolUp.Recursos {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modelo.SchoolUp.Recursos.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acesso criado com sucesso!.
        /// </summary>
        public static string AcessoCriado {
            get {
                return ResourceManager.GetString("AcessoCriado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acesso não identificado!.
        /// </summary>
        public static string AcessoNaoIdentificado {
            get {
                return ResourceManager.GetString("AcessoNaoIdentificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a alteração.
        /// </summary>
        public static string AlteracaoBD {
            get {
                return ResourceManager.GetString("AlteracaoBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O arquivo {0} possui uma extensão inválida. As extensões válidas são: {1}!.
        /// </summary>
        public static string ArquivoExtensaoInvalida {
            get {
                return ResourceManager.GetString("ArquivoExtensaoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O arquivo não deve exceder o tamanho máximo de 1MB!.
        /// </summary>
        public static string ArquivoTamanhoMaximo {
            get {
                return ResourceManager.GetString("ArquivoTamanhoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Os caracteres {0} não são permitidos para o campo {1}!.
        /// </summary>
        public static string CampoCaracteresProibidos {
            get {
                return ResourceManager.GetString("CampoCaracteresProibidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} possui uma data inválida!.
        /// </summary>
        public static string CampoDataInvalida {
            get {
                return ResourceManager.GetString("CampoDataInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve estar entre {1} e {2}!.
        /// </summary>
        public static string CampoEntre {
            get {
                return ResourceManager.GetString("CampoEntre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} não pode exceder {1} caracteres!.
        /// </summary>
        public static string CampoExcessoCaracteres {
            get {
                return ResourceManager.GetString("CampoExcessoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} não pode exceder {1} caracteres, incluindo caracteres ocultos relacionados à formatação!.
        /// </summary>
        public static string CampoExcessoCaracteresDescricao {
            get {
                return ResourceManager.GetString("CampoExcessoCaracteresDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo {0} inválido.
        /// </summary>
        public static string CampoInvalido {
            get {
                return ResourceManager.GetString("CampoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser maior ou igual aos anteriores!.
        /// </summary>
        public static string CampoMaiorIgualAnterior {
            get {
                return ResourceManager.GetString("CampoMaiorIgualAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser maior ou igual ao campo {1}!.
        /// </summary>
        public static string CampoMaiorIgualCampo {
            get {
                return ResourceManager.GetString("CampoMaiorIgualCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser maior que {1}!.
        /// </summary>
        public static string CampoMaiorQue {
            get {
                return ResourceManager.GetString("CampoMaiorQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser menor ou igual a {1}!.
        /// </summary>
        public static string CampoMenorIgualA {
            get {
                return ResourceManager.GetString("CampoMenorIgualA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser menor ou igual ao campo {1}!.
        /// </summary>
        public static string CampoMenorIgualCampo {
            get {
                return ResourceManager.GetString("CampoMenorIgualCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser menor ou igual a hoje!.
        /// </summary>
        public static string CampoMenorIgualHoje {
            get {
                return ResourceManager.GetString("CampoMenorIgualHoje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser menor ou igual que {1}!.
        /// </summary>
        public static string CampoMenorIgualQue {
            get {
                return ResourceManager.GetString("CampoMenorIgualQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} é obrigatório!.
        /// </summary>
        public static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} é obrigatório quando o campo {1} estiver preenchido!.
        /// </summary>
        public static string CampoObrigatorioPorOutro {
            get {
                return ResourceManager.GetString("CampoObrigatorioPorOutro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} aceita somente letras!.
        /// </summary>
        public static string CampoSomenteLetras {
            get {
                return ResourceManager.GetString("CampoSomenteLetras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ter tamanho entre {2} e {1}!.
        /// </summary>
        public static string CampoTamanhoEntre {
            get {
                return ResourceManager.GetString("CampoTamanhoEntre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;br /&gt;.
        /// </summary>
        public static string CaracterePulaLinha {
            get {
                return ResourceManager.GetString("CaracterePulaLinha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Consulta.
        /// </summary>
        public static string ConsultaBD {
            get {
                return ResourceManager.GetString("ConsultaBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Inválida.
        /// </summary>
        public static string DataInvalida {
            get {
                return ResourceManager.GetString("DataInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O arquivo não foi encontrado!.
        /// </summary>
        public static string DownloadArquivoInexistente {
            get {
                return ResourceManager.GetString("DownloadArquivoInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email com a nova senha enviado!.
        /// </summary>
        public static string EmailEnviado {
            get {
                return ResourceManager.GetString("EmailEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atenção! Um email foi enviado mas ocorreu um erro ao gerar a nova senha. .
        /// </summary>
        public static string EmailEnviadoSenhaNaoAlterada {
            get {
                return ResourceManager.GetString("EmailEnviadoSenhaNaoAlterada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email já cadastrado!.
        /// </summary>
        public static string EmailExistente {
            get {
                return ResourceManager.GetString("EmailExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email não cadastrado!.
        /// </summary>
        public static string EmailInexistente {
            get {
                return ResourceManager.GetString("EmailInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro inesperado e o email não foi enviado! .
        /// </summary>
        public static string EmailNaoEnviado {
            get {
                return ResourceManager.GetString("EmailNaoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esta página encontra-se em construção..
        /// </summary>
        public static string EmConstrucao {
            get {
                return ResourceManager.GetString("EmConstrucao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro.
        /// </summary>
        public static string Erro {
            get {
                return ResourceManager.GetString("Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro no acesso ao banco de dados durante a {0} do objeto!.
        /// </summary>
        public static string ErroBD {
            get {
                return ResourceManager.GetString("ErroBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro inesperado!.
        /// </summary>
        public static string ErroInesperado {
            get {
                return ResourceManager.GetString("ErroInesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Favor entrar em contato com o suporte e informar o código {0}.
        /// </summary>
        public static string ErroSuporte {
            get {
                return ResourceManager.GetString("ErroSuporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} {1} não pode exceder {2} anexos!.
        /// </summary>
        public static string ExcessoAnexos {
            get {
                return ResourceManager.GetString("ExcessoAnexos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} {1} não pode exceder {2} caracteres!.
        /// </summary>
        public static string ExcessoCaracteres {
            get {
                return ResourceManager.GetString("ExcessoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} excluíd{1}!.
        /// </summary>
        public static string ExcluidoSucesso {
            get {
                return ResourceManager.GetString("ExcluidoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione ao menos um registro para excluir!.
        /// </summary>
        public static string ExcluirSemSelecionar {
            get {
                return ResourceManager.GetString("ExcluirSemSelecionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a exclusão.
        /// </summary>
        public static string ExclusaoBD {
            get {
                return ResourceManager.GetString("ExclusaoBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formato não reconhecido!.
        /// </summary>
        public static string FormatoIncorreto {
            get {
                return ResourceManager.GetString("FormatoIncorreto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} gravad{1}!.
        /// </summary>
        public static string GravadoSucesso {
            get {
                return ResourceManager.GetString("GravadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a inclusão.
        /// </summary>
        public static string InclusaoBD {
            get {
                return ResourceManager.GetString("InclusaoBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login efetuado com sucesso!.
        /// </summary>
        public static string LoginEfetuado {
            get {
                return ResourceManager.GetString("LoginEfetuado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login já cadastrado!.
        /// </summary>
        public static string LoginExistente {
            get {
                return ResourceManager.GetString("LoginExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logout efetuado com sucesso!.
        /// </summary>
        public static string LogoutEfetuado {
            get {
                return ResourceManager.GetString("LogoutEfetuado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Os campos Matrícula ou Data de Nascimento não correspondem ao aluno selecionado! .
        /// </summary>
        public static string MatriculaNascimentoNaoCorrespondem {
            get {
                return ResourceManager.GetString("MatriculaNascimentoNaoCorrespondem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} Por favor, repita a operação. Caso o erro persista, entre em contato com o suporte técnico e informe o código: .
        /// </summary>
        public static string MensagemRetorno {
            get {
                return ResourceManager.GetString("MensagemRetorno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum {0} ativo encontrado!.
        /// </summary>
        public static string ObjetoExcluidoInativo {
            get {
                return ResourceManager.GetString("ObjetoExcluidoInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum {0} encontrado!.
        /// </summary>
        public static string ObjetoNaoEncontrado {
            get {
                return ResourceManager.GetString("ObjetoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum dado foi carregado ou o item não existe mais!.
        /// </summary>
        public static string ObjetoNulo {
            get {
                return ResourceManager.GetString("ObjetoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preencha com {0} {1} ou {2} {3}.
        /// </summary>
        public static string PeloMenosUmaOpcao {
            get {
                return ResourceManager.GetString("PeloMenosUmaOpcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seu perfil não tem permissão para executar esta ação..
        /// </summary>
        public static string PerfilSemAcesso {
            get {
                return ResourceManager.GetString("PerfilSemAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a pesquisa.
        /// </summary>
        public static string PesquisaBD {
            get {
                return ResourceManager.GetString("PesquisaBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} já cadastrad{1} para {2} {3}!.
        /// </summary>
        public static string RegistroCadastrado {
            get {
                return ResourceManager.GetString("RegistroCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro excluído com sucesso!.
        /// </summary>
        public static string RegistroExcluidoSucesso {
            get {
                return ResourceManager.GetString("RegistroExcluidoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} {1} informad{2} já existe!.
        /// </summary>
        public static string RegistroExistente {
            get {
                return ResourceManager.GetString("RegistroExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro gravado com sucesso!.
        /// </summary>
        public static string RegistroGravadoSucesso {
            get {
                return ResourceManager.GetString("RegistroGravadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} {1} não pode ser excluíd{2} pois está selecionad{3} por um{4} {5}!.
        /// </summary>
        public static string RegistroRelacionado {
            get {
                return ResourceManager.GetString("RegistroRelacionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seleção.
        /// </summary>
        public static string SelecaoBD {
            get {
                return ResourceManager.GetString("SelecaoBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário não possui acesso ao sistema!.
        /// </summary>
        public static string SemAcesso {
            get {
                return ResourceManager.GetString("SemAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário não possui acesso a esta página!.
        /// </summary>
        public static string SemPermissao {
            get {
                return ResourceManager.GetString("SemPermissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum registro encontrado!.
        /// </summary>
        public static string SemRegistroEncontrado {
            get {
                return ResourceManager.GetString("SemRegistroEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum item foi selecionado ou o item não existe mais!.
        /// </summary>
        public static string SemSelecao {
            get {
                return ResourceManager.GetString("SemSelecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha alterada com sucesso!.
        /// </summary>
        public static string SenhaAlterada {
            get {
                return ResourceManager.GetString("SenhaAlterada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha atual incorreta..
        /// </summary>
        public static string SenhaNaoAlterada {
            get {
                return ResourceManager.GetString("SenhaNaoAlterada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Nova senha deve conter 8 caracteres com pelo menos uma letra maiúscula e uma minúscula, um número e um caractere especial!.
        /// </summary>
        public static string SenhaRegex {
            get {
                return ResourceManager.GetString("SenhaRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} e {1} são diferentes!.
        /// </summary>
        public static string SenhasDiferentes {
            get {
                return ResourceManager.GetString("SenhasDiferentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua sessão expirou! Favor efetuar novo login..
        /// </summary>
        public static string SessaoExpirada {
            get {
                return ResourceManager.GetString("SessaoExpirada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Um usuário só pode gerenciar dados de sua própria conta!.
        /// </summary>
        public static string SomenteSuaConta {
            get {
                return ResourceManager.GetString("SomenteSuaConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O arquivo {0} não pode ser vazio..
        /// </summary>
        public static string UploadArquivoVazio {
            get {
                return ResourceManager.GetString("UploadArquivoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione apenas um arquivo!.
        /// </summary>
        public static string UploadSomenteUm {
            get {
                return ResourceManager.GetString("UploadSomenteUm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário bloqueado!.
        /// </summary>
        public static string UsuarioBloqueado {
            get {
                return ResourceManager.GetString("UsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não autenticado!.
        /// </summary>
        public static string UsuarioNaoAutenticado {
            get {
                return ResourceManager.GetString("UsuarioNaoAutenticado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário ou senha incorretos!.
        /// </summary>
        public static string UsuarioSenhaIncorreto {
            get {
                return ResourceManager.GetString("UsuarioSenhaIncorreto", resourceCulture);
            }
        }
    }
}
